client_config_backend: settings
client_config:
  client_id: 853827615429-8aa9nb1spngqn0293hg5l79mfk7ihd3e.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json 

get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive